from setuptools import setup, find_packages

setup(
    name="django-api-utils",
    version="1.0.0",
    description="A Django library for common API utilities.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Begüm Akbay",
    author_email="begum@mosaic.ie",
    url="https://github.com/mosaic/django-api-utils",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "asgiref>=3.8.1,<4.0",
        "cuid>=0.4,<1.0",
        "Django>=5.1.5,<6.0",
        "django-charid-field>=0.4,<1.0",
        "djangorestframework>=3.15.2,<4.0",
        "djangorestframework-simplejwt>=5.5.0,<6.0",
        "holidays>=0.65,<1.0",
        "phonenumbers>=9.0.3,<10.0",
        "PyJWT>=2.9.0,<3.0",
        "python-dateutil>=2.9.0,<3.0",
        "pytz>=2024.2,<2025.0",
        "six>=1.17.0,<2.0",
        "sqlparse>=0.5.3,<1.0",
        "typing_extensions>=4.12.2,<5.0",
    ],
    python_requires=">=3.10, <4",
    classifiers=[
        "Programming Language :: Python :: 3.10",
        "Framework :: Django",
        "License :: OSI Approved :: MIT License",
    ],
)